import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/layout/navbar/NavBar";
import Footer from "@/layout/footer/Footer";


export const metadata: Metadata = {
  title: "Movie Fest",
  description: "Generated by Paz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={''}>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
